#In dieser Datei befinden sich alle wichtigen Einstellungen für das Programm
#Dimension des Fensters
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600
CREATURE_SIZE = 7

#PARAMETER DER SIMULATION
POPULATION_SIZE = 150
INFECTED_PERCENTAGE_AT_START = 0.05 #0-1
INFECTON_CHANCE = 0.7 #0-1
INFECTION_DISTANCE = 16
HEALING_DURATION = 7

CREATURE_SPEED = 0.045


#Versammlungs Hotspot
VERSAMMLUNGS_HOTSPOT = True

HOTSPOT_ZONE_SIZE = 50
HOTSPOT_VISITING_CHANCE = 0.75 #0-1
HOTSPOT_SIZE =  20
HOTSPOT_ZONE_LEFT = int(SCREEN_WIDTH*3/4 - HOTSPOT_SIZE)
HOTSPOT_ZONE_TOP = int(SCREEN_HEIGHT/2 - HOTSPOT_SIZE)


#Quarantäne
QUARANTINE = False
TIME_TO_QUARANTINE = 1.6

QUARANTINE_SIZE = 130
MOVE_TO_QUARANTINE_SPEED = 3
SPEED_IN_QUARANTINE = 0.02
QUARANTINE_CHANCE = 0.7 #0-1


#-----------------------------------------------------------------------------


#Daten speichern
SAVE_DATA = False

#Farben/Aussehen
CREATURE_COLOR = (0, 179, 0)
HEALTHY_CREATURE_COLOR = (66, 135, 245)
SICK_CREATURE_COLOR = (255, 0, 0)
IMMUNE_CREATURE_COLOR = (255, 218, 0)
FONT_COLOR = (77, 60, 145)
BG_COLOR = (21, 15, 44)
LINIEN_FARBE = (220, 220, 220)
INFECTING_ANIMATION_COLOR = (255, 255, 255)
ANIMATIONEN = True
AUTO_SHUTDOWN = False


#Animationen
CIRCLE_GROWTH_RATE = 0.04
CIRCLE_MAX_RADIUS = INFECTION_DISTANCE * 0.7
CIRCLE_MIN_RADIUS = CREATURE_SIZE

DISTANCE_CHECK_TIME_MS = 300
SHUTDOWN_TIME = 20

#Chart-Einstellungen
CHART_WIDTH = SCREEN_WIDTH/2 - 200
CHART_HEIGHT = SCREEN_HEIGHT - 200
CHART_X = 30
CHART_Y = 30
CHART_UPDATE_TIME = 35
CHART_MARK_LENGTH = 8
MAX_DATA = 40


#Abstand Berechnung
GRID_SIZE = 200

#R-naught
R_UPDATE_INTERVALL = 2450 #in Millisekunden